import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Dancing_Script, Roboto, Exo, Montserrat, Geist, Geist_Mono } from 'next/font/google'
import "@/src/app/globals.css"

const dancingScript = Dancing_Script({
    subsets: ['latin'],
    variable: '--font-dancing'
})

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    variable: '--font-roboto'
})

const exo = Exo({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: '--font-exo'
})

const montserrat = Montserrat({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: '--font-montserrat'
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.variable} ${roboto.variable} ${exo.variable} ${montserrat.variable} antialiased`}
      >
        {children}
        {modal}
      </body>
    </html>
  );
}
